---
# tasks file for roles/install_docker
- name: install prerequisites
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes

- name: Create /etc/apt/keyrings directory with permissions
  ansible.builtin.file:
    path:  /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add an Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/keyrings/docker.gpg

- name: Change signing key permission
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.gpg
    mode: a+r

- name: Add docker repo
  vars:
    deb_architecture: { "armv6l": "armhf", "armv7l": "armhf", "aarch64": "arm64", "x86_64": "amd64", "i386": "i386" }
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes

- name: "Appending the group 'docker' the {{ ansible_user }} groups"
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
